blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from blogapp.views import user_profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', user_profile, name='user_profile'),
    path('', include('blogapp.urls')),
    
    
]

blog/blogapp/urls.py
from django.urls import path
from blogapp import views

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('blogs/create/', views.blog_create, name='blog_create'),
    path('blogs/<int:pk>/', views.blog_detail, name='blog_detail'),
    path('blogs/<int:pk>/update/', views.blog_update, name='blog_update'),
    path('blogs/<int:pk>/delete/', views.blog_delete, name='blog_delete'),
    path('blogs/<int:blog_pk>/subblogs/create/', views.subblog_create, name='subblog_create'),
]

blog/blogapp/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class SubBlog(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()


blog/blogapp/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Blog, SubBlog


@login_required
def blog_list(request):
    blogs = Blog.objects.filter(author=request.user)
    return render(request, 'blog_list.html', {'blogs': blogs})

@login_required
def blog_detail(request, pk):
    blog = get_object_or_404(Blog, pk=pk, author=request.user)
    return render(request, 'blog_detail.html', {'blog': blog})

@login_required
def blog_create(request):
    if request.method == 'POST':
        blog = Blog.objects.create(
            title=request.POST['title'],
            content=request.POST['content'],
            author=request.user
        )
        return redirect('blog_detail', pk=blog.pk)
    return render(request, 'blog_create.html')

@login_required
def blog_update(request, pk):
    blog = get_object_or_404(Blog, pk=pk, author=request.user)
    if request.method == 'POST':
        blog.title = request.POST['title']
        blog.content = request.POST['content']
        blog.save()
        return redirect('blog_detail', pk=blog.pk)
    return render(request, 'blog_update.html', {'blog': blog})

@login_required
def blog_delete(request, pk):
    blog = get_object_or_404(Blog, pk=pk, author=request.user)
    if request.method == 'POST':
        blog.delete()
        return redirect('blog_list')
    return render(request, 'blog_delete.html', {'blog': blog})

@login_required
def subblog_create(request, blog_pk):
    blog = get_object_or_404(Blog, pk=blog_pk, author=request.user)
    if request.method == 'POST':
        SubBlog.objects.create(
            blog=blog,
            title=request.POST['title'],
            content=request.POST['content']
        )
        return redirect('blog_detail', pk=blog.pk)
    return render(request, 'subblog_create.html', {'blog': blog})

@login_required
def user_profile(request):
    user = request.user
    return render(request, 'user_profile.html', {'user': user})

blog/blogapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>My Website</title>
    <!-- CSS and other meta tags -->
</head>
<body>
    <header>
        <!-- Your header content goes here -->
        <h1>My Website</h1>
        <nav>
            <!-- Navigation links -->
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/blog/">Blog</a></li>
                <li><a href="/accounts/profile/">Profile</a></li>
                <!-- Other navigation links -->
            </ul>
        </nav>
    </header>

    <div class="content">
        <!-- The content block where specific page content will be inserted -->
        {% block content %}
        {% endblock %}
    </div>

    <footer>
        <!-- Your footer content goes here -->
        <p>&copy; 2023 My Website. All rights reserved.</p>
    </footer>

    <!-- Scripts and other JavaScript code -->
</body>
</html>

blog/blogapp/templates/blog_create.html
<h1>Create a new blog</h1>

<form method="post" action="">
  {% csrf_token %}
  <label for="title">Title:</label><br>
  <input type="text" id="title" name="title"><br>
  <label for="content">Content:</label><br>
  <textarea id="content" name="content"></textarea><br>
  <input type="submit" value="Create">
</form>

blog/blogapp/templates/blog_delete.html
<h1>Delete blog</h1>

<p>Are you sure you want to delete the blog "{{ blog.title }}"?</p>

<form method="post" action="">
  {% csrf_token %}
  <input type="submit" value="Delete">
</form>

blog/blogapp/templates/blog_detail.html
<h1>{{ blog.title }}</h1>

<p>{{ blog.content }}</p>

<a href="{% url 'blog_update' blog.pk %}">Edit</a>
<a href="{% url 'blog_delete' blog.pk %}">Delete</a>

<hr>

<h2>Sub-blogs</h2>

<ul>
  {% for subblog in blog.subblog_set.all %}
    <li>
      <h3>{{ subblog.title }}</h3>
      <p>{{ subblog.content }}</p>
    </li>
  {% empty %}
    <li>No sub-blogs found.</li>
  {% endfor %}
</ul>

<a href="{% url 'subblog_create' blog.pk %}">Add a sub-blog</a>

blog/blogapp/templates/blog_list.html
<h1>My Blogs</h1>

<ul>
  {% for blog in blogs %}
    <li><a href="{% url 'blog_detail' blog.pk %}">{{ blog.title }}</a></li>
  {% empty %}
    <li>No blogs found.</li>
  {% endfor %}
</ul>

<a href="{% url 'blog_create' %}">Create a new blog</a>

blog/blogapp/templates/blog_update.html
<h1>Edit blog</h1>

<form method="post" action="">
  {% csrf_token %}
  <label for="title">Title:</label><br>
  <input type="text" id="title" name="title" value="{{ blog.title }}"><br>
  <label for="content">Content:</label><br>
  <textarea id="content" name="content">{{ blog.content }}</textarea><br>
  <input type="submit" value="Save">
</form>

blog/blogapp/templates/subblog_create.html
<h1>Add a sub-blog to "{{ blog.title }}"</h1>

<form method="post" action="">
  {% csrf_token %}
  <label for="title">Title:</label><br>
  <input type="text" id="title" name="title"><br>
  <label for="content">Content:</label><br>
  <textarea id="content" name="content"></textarea><br>
  <input type="submit" value="Create">
</form>

blog/blogapp/templates/user_profile.html
{% extends 'base.html' %}
{% block content %}
<h2>User Profile</h2>
<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<!-- Additional user profile information can be displayed here -->
{% endblock %}